# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube
import urllib.request
from pytube.cli import on_progress
import sys
import time
from threading import Thread


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 1015)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 900))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainFrame_2 = QtWidgets.QFrame(self.mainFrame)
        self.mainFrame_2.setMinimumSize(QtCore.QSize(1130, 995))
        self.mainFrame_2.setMaximumSize(QtCore.QSize(1130, 995))
        self.mainFrame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mainFrame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mainFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame_2.setObjectName("mainFrame_2")
        self.baixarVideoDoYoutubeLabel = QtWidgets.QLabel(self.mainFrame_2)
        self.baixarVideoDoYoutubeLabel.setGeometry(QtCore.QRect(320, 180, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(24)
        self.baixarVideoDoYoutubeLabel.setFont(font)
        self.baixarVideoDoYoutubeLabel.setObjectName("baixarVideoDoYoutubeLabel")
        self.baixarVideoDoYoutubeLabel.setStyleSheet("font: 75 italic 30pt Arial;")
        self.inputLinkColorFrame = QtWidgets.QFrame(self.mainFrame_2)
        self.inputLinkColorFrame.setGeometry(QtCore.QRect(50, 240, 871, 91))
        self.inputLinkColorFrame.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.inputLinkColorFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputLinkColorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputLinkColorFrame.setObjectName("inputLinkColorFrame")
        self.inputLinkFrame = QtWidgets.QFrame(self.inputLinkColorFrame)
        self.inputLinkFrame.setGeometry(QtCore.QRect(10, 10, 851, 71))
        self.inputLinkFrame.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.inputLinkFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputLinkFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputLinkFrame.setObjectName("inputLinkFrame")
        self.inputLineEdit = QtWidgets.QLineEdit(self.inputLinkFrame)
        self.inputLineEdit.setGeometry(QtCore.QRect(10, 10, 831, 51))
        self.inputLineEdit.setStyleSheet("QLineEdit {\n"
"    font: 14pt \"Arial\";\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: rgb(255, 255, 255)\n"
"}\n"
"")
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.downloadButton = QtWidgets.QPushButton(self.mainFrame_2)
        self.downloadButton.setGeometry(QtCore.QRect(910, 240, 121, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.downloadButton.setFont(font)
        self.downloadButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(209, 34, 27);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 16pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 80, 80);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 16pt \"Arial\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(209, 34, 27);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 16pt \"Arial\";\n"
"}")
        self.downloadButton.setObjectName("downloadButton")
        self.errorFrame = QtWidgets.QFrame(self.mainFrame_2)
        self.errorFrame.setGeometry(QtCore.QRect(40, 120, 1011, 51))
        self.errorFrame.setStyleSheet("QFrame{\n"
"    border-radius: 3px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.errorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.errorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.errorFrame.setObjectName("errorFrame")
        self.errorLabel = QtWidgets.QLabel(self.errorFrame)
        self.errorLabel.setGeometry(QtCore.QRect(10, 10, 861, 31))
        self.errorLabel.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 14pt \"Arial Black\";")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.closeErrorPopUpPushButton = QtWidgets.QPushButton(self.errorFrame)
        self.closeErrorPopUpPushButton.setGeometry(QtCore.QRect(960, 10, 41, 31))
        self.closeErrorPopUpPushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(85, 0, 0);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 10pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(118, 0, 0);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 87 11pt \"Arial\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(85, 0, 0);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 10pt \"Arial\";\n"
"}")
        self.closeErrorPopUpPushButton.setObjectName("closeErrorPopUpPushButton")
        self.confirmationFrame = QtWidgets.QFrame(self.mainFrame_2)
        self.confirmationFrame.setGeometry(QtCore.QRect(50, 340, 1001, 631))
        self.confirmationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirmationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirmationFrame.setObjectName("confirmationFrame")
        self.downloadingFrame = QtWidgets.QFrame(self.confirmationFrame)
        self.downloadingFrame.setGeometry(QtCore.QRect(360, 500, 261, 71))
        self.downloadingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.downloadingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.downloadingFrame.setObjectName("downloadingFrame")
        self.baixandoLabel = QtWidgets.QLabel(self.downloadingFrame)
        self.baixandoLabel.setGeometry(QtCore.QRect(80, 10, 111, 21))
        self.baixandoLabel.setStyleSheet("font: 14pt \"Arial\";\n"
"color: rgb(74, 223, 0);")
        self.baixandoLabel.setObjectName("baixandoLabel")
        self.downloadingProgressBar = QtWidgets.QProgressBar(self.downloadingFrame)
        self.downloadingProgressBar.setGeometry(QtCore.QRect(7, 42, 251, 21))
        self.downloadingProgressBar.setProperty("value", 24)
        self.downloadingProgressBar.setObjectName("downloadingProgressBar")
        self.videoTitleLabel_2 = QtWidgets.QLabel(self.confirmationFrame)
        self.videoTitleLabel_2.setGeometry(QtCore.QRect(20, 10, 961, 41))
        self.videoTitleLabel_2.setStyleSheet("font: 14pt \"Arial\";")
        self.videoTitleLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.videoTitleLabel_2.setScaledContents(False)
        self.videoTitleLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.videoTitleLabel_2.setIndent(-1)
        self.videoTitleLabel_2.setObjectName("videoTitleLabel_2")
        self.thumbnailFrame = QtWidgets.QFrame(self.confirmationFrame)
        self.thumbnailFrame.setGeometry(QtCore.QRect(20, 40, 971, 411))
        self.thumbnailFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.thumbnailFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.thumbnailFrame.setObjectName("thumbnailFrame")
        self.thumbnailLabel = QtWidgets.QLabel(self.thumbnailFrame)
        self.thumbnailLabel.setGeometry(QtCore.QRect(130, 60, 671, 311))
        self.thumbnailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.thumbnailLabel.setObjectName("thumbnailLabel")
        self.videoBaixadoEmLabel = QtWidgets.QLabel(self.confirmationFrame)
        self.videoBaixadoEmLabel.setGeometry(QtCore.QRect(300, 570, 161, 31))
        self.videoBaixadoEmLabel.setStyleSheet("font: 14pt \"Arial\";")
        self.videoBaixadoEmLabel.setObjectName("videoBaixadoEmLabel")
        self.pathLabel = QtWidgets.QLabel(self.confirmationFrame)
        self.pathLabel.setGeometry(QtCore.QRect(460, 570, 441, 31))
        self.pathLabel.setStyleSheet("font: 14pt \"Arial\";")
        self.pathLabel.setObjectName("pathLabel")
        self.confirmPushButton = QtWidgets.QPushButton(self.confirmationFrame)
        self.confirmPushButton.setGeometry(QtCore.QRect(280, 460, 411, 31))
        self.confirmPushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(37, 236, 2);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 255, 0);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(37, 236, 2);\n"
"    color: rgb(245, 245, 245);\n"
"    border-radius: 5px;\n"
"    font: 75 14pt \"Arial\";\n"
"}\n"
"")
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.pathLabel.raise_()
        self.downloadingFrame.raise_()
        self.thumbnailFrame.raise_()
        self.confirmPushButton.raise_()
        self.videoTitleLabel_2.raise_()
        self.videoBaixadoEmLabel.raise_()
        self.titleFrame = QtWidgets.QFrame(self.mainFrame_2)
        self.titleFrame.setGeometry(QtCore.QRect(20, 20, 1021, 50))
        self.titleFrame.setMinimumSize(QtCore.QSize(1021, 50))
        self.titleFrame.setMaximumSize(QtCore.QSize(1021, 40))
        self.titleFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.titleLabel = QtWidgets.QLabel(self.titleFrame)
        self.titleLabel.setGeometry(QtCore.QRect(150, 0, 291, 41))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.creditsLabel = QtWidgets.QLabel(self.titleFrame)
        self.creditsLabel.setGeometry(QtCore.QRect(880, 20, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(True)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setObjectName("creditsLabel")
        self.inputLinkColorFrame.raise_()
        self.baixarVideoDoYoutubeLabel.raise_()
        self.downloadButton.raise_()
        self.confirmationFrame.raise_()
        self.errorFrame.raise_()
        self.titleFrame.raise_()
        self.horizontalLayout.addWidget(self.mainFrame_2)
        self.verticalLayout.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.inputLinkColorFrame.raise_()
        self.baixarVideoDoYoutubeLabel.raise_()
        self.downloadButton.raise_()
        self.errorFrame.raise_()
        self.errorFrame.hide()
        self.confirmationFrame.raise_()
        self.confirmationFrame.hide()
        self.mainFrame.raise_()
        self.titleFrame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        
        #
        #
        # EVENTS
        #
        #
        
        # Link do vídeo
        def catch_video(link):               
                video = YouTube(link)
                self.errorFrame.hide()
                return video
                        
        def confirmation_video():
                try:
                        video = catch_video(self.inputLineEdit.text())
                        self.errorFrame.hide()
                        video_thumbnail = video.thumbnail_url
                        video_title = video.title
                        urllib.request.urlretrieve(video_thumbnail, "thumbnail_last_video.png")
                        self.videoTitleLabel_2.setText(video_title)
                        self.thumbnailLabel.setPixmap(QtGui.QPixmap("thumbnail_last_video.png"))
                        self.downloadingFrame.hide()
                        self.videoBaixadoEmLabel.hide()
                        self.pathLabel.hide()
                        self.confirmationFrame.show() 
                        return video
                except:
                        error_video_catch_thumbnail = "Erro: Link incorreto"
                        self.errorFrame.show()
                        self.errorLabel.setText(error_video_catch_thumbnail)        
        
        def progress_bar_func():
                self.downloadingFrame.show()
                progress = 1
                for progress in range(101):
                        self.downloadingProgressBar.setValue(progress)
                        progress += 1
                        time.sleep(0.015)
                self.baixandoLabel.setText("Concluído!")
                self.videoBaixadoEmLabel.show()
                path = "Downloads"
                self.pathLabel.setText("VideoDownloader/" + str(path))
                self.pathLabel.show()
                
        def download_video():
                self.baixandoLabel.show()
                video = confirmation_video() # Armazenando o retorno da função na variável
                video_highest_resolution = video.streams.get_highest_resolution()
                path = "Downloads"
                video_highest_resolution.download(path)
                Thread(target=progress_bar_func).start()
        
        # Botão de pegar o video
        self.downloadButton.clicked.connect(lambda: confirmation_video())
        
        # Botão para realizar o download
        self.confirmPushButton.clicked.connect(lambda: download_video())
        
        # Função para fechar popup
        self.closeErrorPopUpPushButton.clicked.connect(lambda: self.errorFrame.hide())
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.baixarVideoDoYoutubeLabel.setText(_translate("MainWindow", "Baixar vídeo do Youtube"))
        self.inputLineEdit.setPlaceholderText(_translate("MainWindow", "Digite o link do vídeo"))
        self.downloadButton.setText(_translate("MainWindow", "Baixar"))
        self.errorLabel.setText(_translate("MainWindow", "Error Fatal!"))
        self.closeErrorPopUpPushButton.setText(_translate("MainWindow", "X"))
        self.baixandoLabel.setText(_translate("MainWindow", "Baixando..."))
        self.videoTitleLabel_2.setText(_translate("MainWindow", "Título do vídeo"))
        self.thumbnailLabel.setText(_translate("MainWindow", "img"))
        self.videoBaixadoEmLabel.setText(_translate("MainWindow", "Video baixado em:"))
        self.pathLabel.setText(_translate("MainWindow", "path"))
        self.confirmPushButton.setText(_translate("MainWindow", "Confirmar"))
        self.titleLabel.setText(_translate("MainWindow", "VideoDownloader"))
        self.creditsLabel.setText(_translate("MainWindow", "from Pedro Barros"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
